# Generated by Django 5.2.5 on 2025-09-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='priority',
        ),
    ]
